### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by sravya8** [aws/amazon-s3-plugin-for-pytorch#1]
I am trying to install this package as:
pip install --no-cache-dir -U https://aws-s3-plugin.s3.us-west-2.amazonaws.com/binaries/0.0.1/1c3e69e/awsio-0.0.1-cp38-cp38-manylinux1_x86_64.whl

(Grabbed the wheel location from the docker file)

And when I run the test:
bash tests/smoke_tests/import_awsio.sh

I see the following error:
from awsio._version import __version__
ModuleNotFoundError: No module named 'awsio._version'

**Comment by Roshrini** [comment]
which platform are you running it on? Can you provide more details?

**Comment by sravya8** [comment]
I am trying to install it on an ec2 instance. May be there are more prereqs needed?

**Comment by Roshrini** [comment]
I recommend using following containers for no-hassle use. You can "docker pull" any of the following container, log into it and start using the plugin directly

`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.9.0-cpu-py38-ubuntu20.04-v1.1`

`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.9.0-gpu-py38-cu111-ubuntu20.04-v1.1`

`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.8.1-cpu-py36-ubuntu18.04-v1.6`

`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.8.1-gpu-py36-cu111-ubuntu18.04-v1.7`

**Comment by jeffwang0516** [comment]
@sravya8 
Try `cd tests/smoke_tests/`, then run `bash import_awsio.sh`

I got the error as well when running in the project root dir, and python imports the local awsio/ package directly instead of the one you installed previously.

**Comment by Saripalle** [comment]
@Roshrini Do you have any timeline on when the wheel would be released?

**Comment by ydaiming** [comment]
Hi all, , I've updated the installation guide for the plugin: https://github.com/aws/amazon-s3-plugin-for-pytorch#installation

However, we're deprecating support for the S3 plugin, and I suggest to try the new `torchdata` S3 IO datapipes. [The S3 IO is upstreamed into `torchdata` package](https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load#readme). We're supporting the new `torchdata` package, and continuously improving user experience and performance of the S3 IO datapipes.
