### ISSUE TITLE
Possible to use with Sagemaker?

### ISSUE THREAD

**Issue by jbohnslav** [aws/amazon-s3-plugin-for-pytorch#11]
Hello,

Is it possible to use this plugin with Sagemaker? In the documentation, it looks like each Pytorch Estimator needs a `.tar.gz` file on S3, which seems incompatible with using this Dataset and keeping the data on S3 (rather than copying and unzipping). https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html

**Comment by ydaiming** [comment]
@jbohnslav 

We're upstreaming the *amazon-s3-plugin-for-pytorch* into the *torchdata* package (https://github.com/pytorch/data/pull/165).
We're dropping support for this plugin.

I'm not sure if I understood you correctly. However, the estimator doesn't seem to require a `.tar.gz` file in your reference. I do see the [PyTorch Model](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html#pytorch-model) needs its `model_data` as a `.tar.gz`, but it's very irrelevant to the Dataset.

**Comment by ydaiming** [comment]
Closing the long non-responding issue.
