### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by zelenadinja** [aws/amazon-s3-plugin-for-pytorch#15]
Hi, what is the easiest way to install this?

**Comment by ydaiming** [comment]
Hi @zelenadinja , I've updated the installation guide for the plugin: https://github.com/aws/amazon-s3-plugin-for-pytorch#installation

However, we're deprecating support for the S3 plugin, and I suggest to try the new `torchdata` S3 IO datapipes. [The S3 IO is upstreamed into `torchdata` package](https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load#readme). We're supporting the new `torchdata` package, and continuously improving user experience and performance of the S3 IO datapipes.
