### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by joytafty** [aws/amazon-s3-plugin-for-pytorch#2]
Where can find a list of s3 uri for prebuilt wheels?

**Comment by Roshrini** [comment]
This plugin is available through following containers:
`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.9.0-cpu-py38-ubuntu20.04-v1.1`

`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.9.0-gpu-py38-cu111-ubuntu20.04-v1.1`

`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.8.1-cpu-py36-ubuntu18.04-v1.6`

`763104351884.dkr.ecr.us-west-2.amazonaws.com/pytorch-training:1.8.1-gpu-py36-cu111-ubuntu18.04-v1.7`

installation instructions from containers are here: https://aws.amazon.com/blogs/machine-learning/announcing-the-amazon-s3-plugin-for-pytorch/

**Comment by ydaiming** [comment]
Hi @joytafty , I've updated the installation guide for the plugin: https://github.com/aws/amazon-s3-plugin-for-pytorch#installation

However, we're deprecating support for the S3 plugin, and I suggest to try the new `torchdata` S3 IO datapipes. [The S3 IO is upstreamed into `torchdata` package](https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load#readme). We're supporting the new `torchdata` package, and continuously improving user experience and performance of the S3 IO datapipes.
