### ISSUE TITLE
Data files being downloaded in working directory

### ISSUE THREAD

**Issue by SamTNeoX** [aws/amazon-s3-plugin-for-pytorch#22]
I've been using the `S3Dataset` classes to read data from S3. It works, however all the image files are downloaded in my working directory when reading the url via             
 `fileobj = self.handler.s3_read(filename)` where `self.handler` is `_pywrap_s3_io.S3Init()`
 https://github.com/aws/amazon-s3-plugin-for-pytorch/blob/919729ca97f154f297e6038177b16cbcc04293ef/awsio/python/lib/io/s3/s3dataset.py#L146
 
Is there a way to specify a different directory to where the images should be downloaded, or re-direct the download to a separate temp directory?

**Comment by ydaiming** [comment]
@SamTNeoX 

We're upstreaming the __amazon-s3-plugin-for-pytorch__ into the __torchdata__ package (https://github.com/pytorch/data/pull/165).
We're dropping support for this plugin.

The current s3 plugin doesn't have this feature, so do the new S3 IO datapipes. We'll backlog this feature request, and update the feature in the new S3 IO datapipes.
