### ISSUE TITLE
How does it compare to the recently released torchdata?

### ISSUE THREAD

**Issue by gcheron** [aws/amazon-s3-plugin-for-pytorch#23]
[Torchdata](https://pytorch.org/blog/pytorch-1.11-released/#introducing-torchdata) includes some DataPipes, the [fsspec](https://pytorch.org/data/0.3.0/torchdata.datapipes.iter.html#io-datapipes) and iopath that allow to connect to cloud providers (such as AWS S3).

How does the **amazon-s3-plugin-for-pytorch** compare to torchdata?

**Comment by ydaiming** [comment]
@gcheron 

We're upstreaming the __amazon-s3-plugin-for-pytorch__ into the __torchdata__ package (https://github.com/pytorch/data/pull/165/).

We're dropping support for this plugin. 

To answer your question, this s3 plugin allows access with s3 urls, while current __torchdata__ package doesn't. the __torchdata__ package will allow s3 url accesses once the PR above is merged.
