### ISSUE TITLE
Where the wheel file

### ISSUE THREAD

**Issue by Di0826** [aws/amazon-s3-plugin-for-pytorch#4]
I am trying to install this plugin by wheel file on Window, but I cant find the wheel file, can you provide an instruction about installing plugin on Window? Think you

**Comment by evanlalo** [comment]
I second this. It'd be great if you could list out the wheel files for each supported python version.

**Comment by ydaiming** [comment]
Hi @Di0826 and @evanlalo , I've updated the installation guide for the plugin: https://github.com/aws/amazon-s3-plugin-for-pytorch#installation

However, we're deprecating support for the S3 plugin, and I suggest to try the new `torchdata` S3 IO datapipes. [The S3 IO is upstreamed into `torchdata` package](https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load#readme). We're supporting the new `torchdata` package, and continuously improving user experience and performance of the S3 IO datapipes.
