### ISSUE TITLE
installation via pip or conda

### ISSUE THREAD

**Issue by vaibhavnayel** [aws/amazon-s3-plugin-for-pytorch#6]
Is there a way to use the package through pip/conda without docker? I'd also like to know what additional steps are needed to set this up in jupyter lab.

**Comment by blakespace** [comment]
seconding this.  So far the plugin seems very limited if we are forced to use it with an aws docker image.

**Comment by Joel-Rootgers** [comment]
thirding this, it would be great if we could get a pip installable package

**Comment by Roshrini** [comment]
for now you can try pip install like this without docker:
https://github.com/aws/deep-learning-containers/blob/master/pytorch/training/docker/1.9/py3/Dockerfile.cpu#L148-L149

**Comment by blakespace** [comment]
```
ubuntu:~/code/amazon-s3-plugin-for-pytorch$ pip install -U  https://aws-s3-plugin.s3.us-west-2.amazonaws.com/binaries/0.0.1/1c3e69e/awsio-0.0.1-cp38-cp38-manylinux1_x86_64.whl
ERROR: awsio-0.0.1-cp38-cp38-manylinux1_x86_64.whl is not a supported wheel on this platform.
WARNING: You are using pip version 21.3; however, version 21.3.1 is available.
You should consider upgrading via the '/home/ubuntu/Envs/doory/bin/python -m pip install --upgrade pip' command.
```

What would be considered a supported platform?  I'm attempting to install on ubuntu,

**Comment by blakespace** [comment]
Nevermind, I found the address:

https://aws-s3-plugin.s3-us-west-2.amazonaws.com/binaries/0.0.1/93fdaed/awsio-0.0.1-cp36-cp36m-manylinux1_x86_64.whl

**Comment by ydaiming** [comment]
Hi all, I've updated the installation guide for the plugin: https://github.com/aws/amazon-s3-plugin-for-pytorch#installation

However, we're deprecating support for the S3 plugin, and I suggest to try the new `torchdata` S3 IO datapipes. [The S3 IO is upstreamed into `torchdata` package](https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load#readme). We're supporting the new `torchdata` package, and continuously improving user experience and performance of the S3 IO datapipes.
