### ISSUE TITLE
ModuleNotFoundError: No module named '_pywrap_s3_io'

### ISSUE THREAD

**Issue by piupiuisland** [aws/amazon-s3-plugin-for-pytorch#7]
Hi,  I run into en error of "ModuleNotFoundError: No module named '_pywrap_s3_io'", is it part of the module? or where can I find it?

**Comment by Roshrini** [comment]
How did you install the package? Can you provide some more info?

**Comment by rehno-lindeque** [comment]
Hi, I'm having the same problem while [attempting to package this for the nix package manager](https://github.com/NixOS/nixpkgs/pull/152465/files).

Would you mind running `ls` on the build path so that I could compare my build output? (shown below)

```
$ ls -R build
build:
bdist.linux-x86_64  lib.linux-x86_64-3.9

build/bdist.linux-x86_64:

build/lib.linux-x86_64-3.9:
aws_io.cpython-39-x86_64-linux-gnu.so  awsio

build/lib.linux-x86_64-3.9/awsio:
__init__.py  _version.py  python

build/lib.linux-x86_64-3.9/awsio/python:
__init__.py  lib

build/lib.linux-x86_64-3.9/awsio/python/lib:
__init__.py  io

build/lib.linux-x86_64-3.9/awsio/python/lib/io:
__init__.py  s3

build/lib.linux-x86_64-3.9/awsio/python/lib/io/s3:
__init__.py  s3dataset.py
```

**Comment by brown2021** [comment]
I am having the same issue

**Comment by ydaiming** [comment]
Hi all, I've updated the installation guide for the plugin: https://github.com/aws/amazon-s3-plugin-for-pytorch#installation

However, we're deprecating support for the S3 plugin, and I suggest to try the new `torchdata` S3 IO datapipes. [The S3 IO is upstreamed into `torchdata` package](https://github.com/pytorch/data/tree/main/torchdata/datapipes/iter/load#readme). We're supporting the new `torchdata` package, and continuously improving user experience and performance of the S3 IO datapipes.
