### ISSUE TITLE
can this plugin working with other s3 storage ,like the ceph s3?

### ISSUE THREAD

**Issue by Stevenyu1982** [aws/amazon-s3-plugin-for-pytorch#8]
i didn't find a place to config the endpoints, wondering if this could also support other s3 storages

**Comment by jeffwang0516** [comment]
Try `export S3_ENDPOINT_URL=your_s3_endpoint`

The env var will be read from here:
https://github.com/aws/amazon-s3-plugin-for-pytorch/blob/master/awsio/csrc/io/s3/s3_io.cpp#L89

**Comment by Stevenyu1982** [comment]
@jeffwang0516 thanks man
